
ignored = ["k8s.io/client-go/pkg/api/errors","k8s.io/client-go/pkg/api/v1","k8s.io/client-go/pkg/api/unversioned", "k8s.io/client-go/pkg/watch"]

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.0"

[[constraint]]
  name = "github.com/vishvananda/netlink"
  version = "v1.0.0"

[[override]]
  name = "k8s.io/client-go"
  revision = "afb4606c45bae77c4dc2c15291d4d7d6d792196c"

[[override]]
  name = "k8s.io/api"
  revision = "81aa34336d28aadc3a8e8da7dfd9258c5157e5e4"

[[override]]
  name = "k8s.io/apimachinery"
  revision = "3b05bbfa0a45413bfa184edbf9af617e277962fb"

[[override]]
  name = "golang.org/x/sys"
  revision = "d8e400bc7db4870d786864138af681469693d18c"

[[override]]
  name = "github.com/vishvananda/netns"
  revision = "be1fbeda19366dea804f00efff2dd73a1642fdcc"
