name: Bazel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.7.5/bazelisk-linux-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazelisk"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazelisk"

    - name: Build with bazel
      run: |
        "${GITHUB_WORKSPACE}/bin/bazelisk" build //...

    - name: Test with bazel
      run: |
        "${GITHUB_WORKSPACE}/bin/bazelisk" test //...
